export const REQUEST_LOOKUPS_VKAPI = "REQUEST_LOOKUPS_VKAPI";
export const START_LOOKUPS_VKAPI = "START_LOOKUPS_VKAPI";
export const SUCCESS_LOOKUPS_VKAPI = "SUCCESS_LOOKUPS_VKAPI";
export const ERROR_LOOKUPS_VKAPI = "ERROR_LOOKUPS_VKAPI";
