import { prefix } from "./config";

export const FETCH_VACATIONS_REQUEST = `${prefix}/FETCH_VACATIONS_REQUEST`;
export const FETCH_VACATIONS_START = `${prefix}/FETCH_VACATIONS_START`;
export const FETCH_VACATIONS_SUCCESS = `${prefix}/FETCH_VACATIONS_SUCCESS`;
export const FETCH_VACATIONS_ERROR = `${prefix}/FETCH_VACATIONS_ERROR`;

export const FETCH_VACATION_REQUEST = `${prefix}/FETCH_VACATION_REQUEST`;
export const FETCH_VACATION_START = `${prefix}/FETCH_VACATION_START`;
export const FETCH_VACATION_SUCCESS = `${prefix}/FETCH_VACATION_SUCCESS`;
export const FETCH_VACATION_ERROR = `${prefix}/FETCH_VACATION_ERROR`;

export const CREATE_VACATION_REQUEST = `${prefix}/CREATE_VACATION_REQUEST`;
export const CREATE_VACATION_START = `${prefix}/CREATE_VACATION_START`;
export const CREATE_VACATION_SUCCESS = `${prefix}/CREATE_VACATION_SUCCESS`;
export const CREATE_VACATION_ERROR = `${prefix}/CREATE_VACATION_ERROR`;

export const UPDATE_VACATION_REQUEST = `${prefix}/UPDATE_VACATION_REQUEST`;
export const UPDATE_VACATION_START = `${prefix}/UPDATE_VACATION_START`;
export const UPDATE_VACATION_SUCCESS = `${prefix}/UPDATE_VACATION_SUCCESS`;
export const UPDATE_VACATION_ERROR = `${prefix}/UPDATE_VACATION_ERROR`;

export const DELETE_VACATION_REQUEST = `${prefix}/DELETE_VACATION_REQUEST`;
export const DELETE_VACATION_START = `${prefix}/DELETE_VACATION_START`;
export const DELETE_VACATION_SUCCESS = `${prefix}/DELETE_VACATION_SUCCESS`;
export const DELETE_VACATION_ERROR = `${prefix}/DELETE_VACATION_ERROR`;

export const FETCH_VACATIONS_FOR_VK_USER_REQUEST = `${prefix}/FETCH_VACATIONS_FOR_VK_USER_REQUEST`;
export const FETCH_VACATIONS_FOR_VK_USER_START = `${prefix}/FETCH_VACATIONS_FOR_VK_USER_START`;
export const FETCH_VACATIONS_FOR_VK_USER_SUCCESS = `${prefix}/FETCH_VACATIONS_FOR_VK_USER_SUCCESS`;
export const FETCH_VACATIONS_FOR_VK_USER_ERROR = `${prefix}/FETCH_VACATIONS_FOR_VK_USER_ERROR`;
